### ISSUE TITLE
Proj Ideas

### ISSUE THREAD

**Issue by vladimirlogachev** [TheOmegaBlack/Chingu-TeamBear6#1]
here

**Comment by vladimirlogachev** [comment]
* something like meetup.com with no payments from users (and no deep history stored, so only limited data storage needed)
* an app to find friends to run outdoors and share tracks (on the map with every internet user).
* e-mail service with web interface
* crazy-fantazy imaginary renderer for react. That renders not to mobile/dom, but something.. Weird)) (maybe sound)
* any game (I never made games before, because I wanted to be non-childish developer and wanted to build "serious applications for busy people". Now I have it in my work, so I do not restrict myself for this collaboration.) Do you want to make a game? 
>but if I could choose I'd like a more serious app

**Comment by vladimirlogachev** [comment]
* slack user simulator (not just a bot) to cheat chingu wizards on slack (so we can completely move to discord)

**Comment by vladimirlogachev** [comment]
* CRM for meeting with a lot of girls (or boys, in reverse) to keep track of who is who, saving notes, planning calls, meetings, grouping and setting goals (like sales plan).
This is not implemented yet, and many people will say that we are bad if we create this. But a lot of people will shamelessly use it.
Dating Management System, like that.

**Comment by vladimirlogachev** [comment]
* encrypted contacts (that could not be restored, could not be shown to other app, like that). No synchronisation, only manually started import / export. Even with only desktop layout will be great (hello electron). Also needed multi-grouping and planning events for this system: calls, meetings. But no communications within the app itself.

**Comment by sachamorgese** [comment]
・I really wanted to create a dating app that can put together people with the same interests when I started studying redux, so I think this idea can work with both the meetup thing and the Management System.

**Comment by sachamorgese** [comment]
I like the idea of a game, but looking at the skills I think we should stick with React and I don't know what kind of interesting game we can squeeze out of that library

**Comment by vladimirlogachev** [comment]
not react, but redux. event happens, and every unit in the game world reacts, like reducer or saga. you make 1 little step forward and zombies all over the globe awaken and make a step in your direction.

**Comment by vladimirlogachev** [comment]
and react can only show all units in view-able territory and their state. but things happen worldwide.

**Comment by vladimirlogachev** [comment]
and if you behave like an evil person, awful things happen to you, and if you are good person, good things happen. good for you, but somewhere far from you.

**Comment by vladimirlogachev** [comment]
* A platform to fing a drummer or bass player. Drummers register for free, guitarists pay 2.99 USD. Singers pay 1.49 USD.

**Comment by sachamorgese** [comment]
I'm both a singer and a guitarist, I don't like this app hahaha

**Comment by vladimirlogachev** [comment]
* well, final idea for today. let's start trading something. I mean, new e-commerce business. And build an e-commerce solution for oursekves from scratch. (there are lots of universal solutions, but we can make one not as an universal solution, but as a custom tool for us. to make custom tool for commerce one should have a commerce, so we can create a shop of whatever and code up everything for it).

**Comment by vladimirlogachev** [comment]
If you are both, then you need drummer the most! pay 3.99 now and save 0.49!

**Comment by kevcomedia** [comment]
* I was thinking of making an app for [p1xt's 2018 speedstudy challenge](https://github.com/P1xt/speedstudy). You pick a project/course/whatever to work on. When you finish, you get points depending on the item you did.

**Comment by sachamorgese** [comment]
・An app that allows you to connect with developers to help you with small projects. We could start it as some kind of help tools for people who are learning programming, like an alternative to stack-overflow or a board, but could be then expanded to be a platform to hire freelancers

**Comment by kevcomedia** [comment]
I think the idea can be generalized, where a user can come up with and publish their own list of activities and points, and a deadline. Then another user will select a list (or lists) to participate in, then do as many activities as they can before the list's deadline.

**Comment by vladimirlogachev** [comment]
sounds pretty, but I don't like races. So do many ither people. I mean: idea of helping others is a challenging game itself - is great. but when you end up with points - ...
questionable thing.

**Comment by kevcomedia** [comment]
yeah, it relies on an honor system

**Comment by tungnt-580** [comment]
dsadsd

**Comment by tungnt-580** [comment]
I like game idea, it can be a puzzle game, like 2048 or Bejeweled, I think it can be done with grid system, and react with state transformation

**Comment by mikeale03** [comment]
I like a web app like edx where people can easy make their own course or tutorial.  They can attach videos, they can make quiz or challenges and add some sort of grading system maybe. People can search this tutorials and answers some quiz and challenges.

**Comment by tungnt-580** [comment]
* A web build something with Drag&Drop, like CVBuilder, or Portfolio builder, .etc
