### ISSUE TITLE
create socket.io with timestamp

### ISSUE THREAD

**Issue by vladimirlogachev** [TheOmegaBlack/Chingu-TeamBear6#11]
to make sure everything works as expected, create a socket.io route '/websockets' that sends object with timestamp (`emit('timestamp`, obj)`) every 10 seconds for every user connected to it.

```
{
   timestamp: 43584584856858365;
}
```

**Comment by mikeale03** [comment]
do i need to attach socket to router or i just use namespace? i'm not good with socket.
