### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by sachamorgese** [TheOmegaBlack/Chingu-TeamBear6#5]
People in charge of backend should start to write down ideas for the database. We will review them together, let's start with a draft.

**Comment by vladimirlogachev** [comment]
just not to forget:
* user has full name and geoposition
* user should have email to get notified
* meeting event has leader (one of user) time, description, phone to call(it is not the same as user's) and geoposition
* there are some unstructured and hidden hashtags
* and there are some structured Interests
* user has several interests with different options of: (distance to go, available for collaboration, wants to be a leader in event)

**Comment by mikeale03** [comment]
```
User
{
 _id
 name
 email
 password
 address
 geolocation
 interests [
  {
    _id
    name
    is_leader: boolean
    is_available:boolean
    max_distance
    
  }
 ]
}

meeting
{
 _id
 members: [
  {
    _id
    name
  }
 ]
 leader {
   _id
   name
 }
 description
 interest:
 hashtags:[#1,#2]
 address
 geolocation
 contact	
}
```
**Any feedback for this schema?**

**Comment by tungnt-580** [comment]
With our discussion, interests need to be a separate entity, and it'll become a collection, right?

**Comment by mikeale03** [comment]
yeah, we can add an interest collection. I don't get the whole picture yet.

**Comment by kevcomedia** [comment]
I'm wondering about the address field in the user schema. Is it a full address, or just a general location?

**Comment by mikeale03** [comment]
address field is full address. geolocation is the lattitude and longitude. i think address will be provided with google map after he points location.

**Comment by VladimirLogachev** [comment]
address not needed.

**Comment by vladimirlogachev** [comment]
```
User
 address // not needed. we will not use it in MVP. 

 interests [
  {
    name // remove
    is_leader: boolean //  wantsToBeLeader: boolean
  }
 ]


meeting
{
 members: [
  {
    name // remove
  }
 ]
 leader {
   name // remove
 }
interest: // interestOrHashtag
hashtags:[#1,#2] // remove
}
```

**Comment by vladimirlogachev** [comment]
meeting should have **suggestedGeoposition** (either a point or an area... it will be last thing to implement)
